version: 2.1

jobs:
  ubuntu18: # Ubuntu 18
    docker:
      - image: ubuntu:18.04
    steps:
      - run:
          name: "Install gcc git cmake"
          command: |
            apt update -y
            apt install -y build-essential git cmake
      - run:
          name: "Install boost"
          command: |
            git clone --recursive https://github.com/boostorg/boost.git
            cd boost
            git checkout tags/boost-1.77.0
            ./bootstrap.sh
            ./b2 install
      - run:
          name: "Install ACT"
          command: |
            apt install -y libedit-dev zlib1g-dev m4
            git clone https://github.com/asyncvlsi/act.git
            cd act
            mkdir install
            export VLSI_TOOLS_SRC=`pwd`
            export ACT_HOME=$VLSI_TOOLS_SRC/install
            echo export VLSI_TOOLS_SRC=`pwd` >> $BASH_ENV
            echo export ACT_HOME=$VLSI_TOOLS_SRC/install >> $BASH_ENV
            ./configure $ACT_HOME
            ./build
            make install
      - run:
          name: "Install Si2 LEF/DEF parser"
          command: |
            git clone https://github.com/asyncvlsi/lefdef.git
            apt-get install -y flex bison
            cd lefdef
            echo '$ACT_HOME' $ACT_HOME
            make
            make install
      - run:
          name: "Install phyDB"
          command: |
            echo '$ACT_HOME' $ACT_HOME
            git clone https://github.com/asyncvlsi/phyDB.git
            cd phyDB
            mkdir build
            cd build
            cmake ..
            make install
workflows:
  build:
    jobs:
      - ubuntu18
