//
// Created by yihangyang on 9/21/21.
//

#ifndef PHYDB_INTERPRETER_H
#define PHYDB_INTERPRETER_H

#include <vector>

#include "scanner.h"

#include "parser.hpp" // autogenerated by Bison,

namespace phydb {

class Interpreter {
public:
    Interpreter();
    int parse();
    void clear();
    void switchInputStream(std::istream *is);
    friend class Parser;
    friend class Scanner;

private:
    void increaseLocation(unsigned int loc);
    unsigned int location() const;

private:
    Scanner m_scanner;
    Parser m_parser;
    unsigned int m_location; // Used by scanner
};

}

#endif //PHYDB_INTERPRETER_H
